//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_BOYAHANETAKIP
    {
        public int Boyahane_Takip_ID { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public string Urun_Barkod { get; set; }
        public Nullable<decimal> Gonderilen_Miktar { get; set; }
        public Nullable<decimal> Gelen_Miktar { get; set; }
        public Nullable<System.DateTime> Gonderim_Tarih { get; set; }
        public Nullable<System.DateTime> Gelis_Tarih { get; set; }
        public string Durum { get; set; }
    
        public virtual ALB_URUNLER ALB_URUNLER { get; set; }
    }
}
