//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_BARKODGUNCELLEME
    {
        public int Kayıt_ID { get; set; }
        public string Urun_Barkod { get; set; }
        public string Eski_Bilgi { get; set; }
        public string Yeni_Bilgi { get; set; }
        public Nullable<System.DateTime> Guncelleme_Tarihi { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
    
        public virtual ALB_PERSONEL ALB_PERSONEL { get; set; }
    }
}
