//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_STOKKONTROL
    {
        public int Stok_Kontrol_ID { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public Nullable<decimal> Mevcut_Stok { get; set; }
        public Nullable<decimal> Minimum_Stok { get; set; }
        public Nullable<decimal> Maximum_Stok { get; set; }
        public Nullable<decimal> Uyarı_Seviyesi { get; set; }
    
        public virtual ALB_URUNLER ALB_URUNLER { get; set; }
    }
}
