//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_PERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALB_PERSONEL()
        {
            this.ALB_BARKODGUNCELLEME = new HashSet<ALB_BARKODGUNCELLEME>();
        }
    
        public int Personel_ID { get; set; }
        public string Personel_Adi { get; set; }
        public string Personel_Soyadi { get; set; }
        public Nullable<int> Personel_TC { get; set; }
        public Nullable<int> Personel_Tel_No { get; set; }
        public string Personel_Mail { get; set; }
        public string Personel_Pozisyon { get; set; }
        public Nullable<int> Departman_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_BARKODGUNCELLEME> ALB_BARKODGUNCELLEME { get; set; }
        public virtual ALB_DEPARTMAN ALB_DEPARTMAN { get; set; }
    }
}
