//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALB_URUNLER()
        {
            this.ALB_BOYAHANETAKIP = new HashSet<ALB_BOYAHANETAKIP>();
            this.ALB_SIPARISDETAY = new HashSet<ALB_SIPARISDETAY>();
            this.ALB_STOKHAREKET = new HashSet<ALB_STOKHAREKET>();
            this.ALB_STOKKONTROL = new HashSet<ALB_STOKKONTROL>();
        }
    
        public int Urun_ID { get; set; }
        public string Urun_Adi { get; set; }
        public string Urun_Barkod { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public Nullable<decimal> Alis_Fiyati { get; set; }
        public Nullable<decimal> Satis_Fiyati { get; set; }
        public string Olcu_Birimi { get; set; }
        public string Stok_Durumu { get; set; }
        public Nullable<decimal> Stok_Miktari { get; set; }
        public Nullable<int> Tedarikci_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_BOYAHANETAKIP> ALB_BOYAHANETAKIP { get; set; }
        public virtual ALB_KATEGORILER ALB_KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_SIPARISDETAY> ALB_SIPARISDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_STOKHAREKET> ALB_STOKHAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_STOKKONTROL> ALB_STOKKONTROL { get; set; }
    }
}
