//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_IS_EMIRLERI
    {
        public int Is_Emri_Id { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public Nullable<System.DateTime> Is_Emri_Tarihi { get; set; }
        public Nullable<System.DateTime> Beklenen_Tamamlanma_Tarihi { get; set; }
        public Nullable<int> Sorumlu_Personel_ID { get; set; }
        public string Durum { get; set; }
    
        public virtual ALB_PERSONEL ALB_PERSONEL { get; set; }
        public virtual ALB_URUNLER ALB_URUNLER { get; set; }
    }
}
