//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_FASON_SIRKETLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALB_FASON_SIRKETLER()
        {
            this.ALB_FASON_TAKIP = new HashSet<ALB_FASON_TAKIP>();
        }
    
        public int Fason_Sirket_ID { get; set; }
        public string Sirket_Adi { get; set; }
        public string Iletisim_Bilgileri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_FASON_TAKIP> ALB_FASON_TAKIP { get; set; }
    }
}
