//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_URETIM_MALIYETLERI
    {
        public int Maliyet_ID { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public string Maliyet_Kalem { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> Birim_Maliyet { get; set; }
        public Nullable<decimal> Toplam_Maliyet { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual ALB_URUNLER ALB_URUNLER { get; set; }
    }
}
