//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALB_MUSTERILER()
        {
            this.ALB_SIPARISLER = new HashSet<ALB_SIPARISLER>();
        }
    
        public int Musteri_ID { get; set; }
        public string Musteri_Adi { get; set; }
        public string Musteri_Soyad { get; set; }
        public string Musteri_Sirket { get; set; }
        public Nullable<int> Musteri_Tel_No { get; set; }
        public string Musteri_Mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_SIPARISLER> ALB_SIPARISLER { get; set; }
    }
}
