//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_HAREKETTIPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALB_HAREKETTIPI()
        {
            this.ALB_STOKHAREKET = new HashSet<ALB_STOKHAREKET>();
        }
    
        public int Hareket_Tip_ID { get; set; }
        public string Hareket_Tipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALB_STOKHAREKET> ALB_STOKHAREKET { get; set; }
    }
}
