//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_SIPARISDETAY
    {
        public int Siparis_Detay_ID { get; set; }
        public Nullable<int> Siparis_ID { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual ALB_SIPARISLER ALB_SIPARISLER { get; set; }
        public virtual ALB_URUNLER ALB_URUNLER { get; set; }
    }
}
