//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_FASON_TAKIP
    {
        public int Fason_Takip_ID { get; set; }
        public Nullable<int> Urun_ID { get; set; }
        public Nullable<int> Fason_Sirket_ID { get; set; }
        public Nullable<decimal> Gonderilen_Miktar { get; set; }
        public Nullable<System.DateTime> Gonderim_Tarihi { get; set; }
        public string Durum { get; set; }
    
        public virtual ALB_FASON_SIRKETLER ALB_FASON_SIRKETLER { get; set; }
        public virtual ALB_URUNLER ALB_URUNLER { get; set; }
    }
}
