//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_NOTLAR
    {
        public int Not_Id { get; set; }
        public string Not_Baslik { get; set; }
        public string Not_Icerik { get; set; }
        public Nullable<bool> Not_Durum { get; set; }
    }
}
