//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_KULLANICIYETKI
    {
        public int Admin_ID { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public string Yetki { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
