//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALBTekstil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ALBER_TEKSTİLEntities : DbContext
    {
        public DB_ALBER_TEKSTİLEntities()
            : base("name=DB_ALBER_TEKSTİLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALB_BARKODGUNCELLEME> ALB_BARKODGUNCELLEME { get; set; }
        public virtual DbSet<ALB_BOYAHANETAKIP> ALB_BOYAHANETAKIP { get; set; }
        public virtual DbSet<ALB_DEPARTMAN> ALB_DEPARTMAN { get; set; }
        public virtual DbSet<ALB_FINANS> ALB_FINANS { get; set; }
        public virtual DbSet<ALB_HAREKETTIPI> ALB_HAREKETTIPI { get; set; }
        public virtual DbSet<ALB_KATEGORILER> ALB_KATEGORILER { get; set; }
        public virtual DbSet<ALB_KULLANICIYETKI> ALB_KULLANICIYETKI { get; set; }
        public virtual DbSet<ALB_MUSTERILER> ALB_MUSTERILER { get; set; }
        public virtual DbSet<ALB_PERSONEL> ALB_PERSONEL { get; set; }
        public virtual DbSet<ALB_SIPARISDETAY> ALB_SIPARISDETAY { get; set; }
        public virtual DbSet<ALB_SIPARISLER> ALB_SIPARISLER { get; set; }
        public virtual DbSet<ALB_STOKHAREKET> ALB_STOKHAREKET { get; set; }
        public virtual DbSet<ALB_STOKKONTROL> ALB_STOKKONTROL { get; set; }
        public virtual DbSet<ALB_URUNLER> ALB_URUNLER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ALB_FASON_SIRKETLER> ALB_FASON_SIRKETLER { get; set; }
        public virtual DbSet<ALB_FASON_TAKIP> ALB_FASON_TAKIP { get; set; }
        public virtual DbSet<ALB_IS_EMIRLERI> ALB_IS_EMIRLERI { get; set; }
        public virtual DbSet<ALB_NOTLAR> ALB_NOTLAR { get; set; }
        public virtual DbSet<ALB_TOPLAM_URETIM_MALIYETLERI> ALB_TOPLAM_URETIM_MALIYETLERI { get; set; }
        public virtual DbSet<ALB_URETIM_MALIYETLERI> ALB_URETIM_MALIYETLERI { get; set; }
        public virtual DbSet<ALB_URUN_DURUM> ALB_URUN_DURUM { get; set; }
    }
}
